### PR TITLE
test pull request, please ignore

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by staticfloat** [comment]
@jlbuild
```
println("test!")
```

**Comment by staticfloat** [comment]
@jlbuild 61a291bf6c4b5997b9b1371a7d3f12a6ce86945a
```
println("test!")
```

**Comment by jlbuild** [comment]
## Status of https://github.com/JuliaLang/julia/commit/61a291bf6c4b5997b9b1371a7d3f12a6ce86945a builds:

| Builder Name | Status | Download | Code Output |
| :----------- | :----: | :------: | :---------: |
| [package_linux32](https://buildtest.e.ip.saba.us/#/builders/39) | [BUILDING](https://buildtest.e.ip.saba.us/#/builders/39/builds/19), started at Wed 22 Feb 2017 01:56:56 PM PST | N/A | N/A |
| [package_linux64](https://buildtest.e.ip.saba.us/#/builders/54) | [BUILDING](https://buildtest.e.ip.saba.us/#/builders/54/builds/17), started at Wed 22 Feb 2017 02:21:42 PM PST | N/A | N/A |
| [package_linuxaarch64](https://buildtest.e.ip.saba.us/#/builders/56) | [PENDING](https://buildtest.e.ip.saba.us/#/buildrequests/208) | N/A | N/A |
| [package_linuxarmv7l](https://buildtest.e.ip.saba.us/#/builders/3) | [ERRORED](https://buildtest.e.ip.saba.us/#/builders/3/builds/23) | N/A | N/A |
| [package_linuxppc64le](https://buildtest.e.ip.saba.us/#/builders/20) | [BUILDING](https://buildtest.e.ip.saba.us/#/builders/20/builds/8), started at Wed 22 Feb 2017 02:22:50 PM PST | N/A | N/A |
| [package_osx64](https://buildtest.e.ip.saba.us/#/builders/1) | [PENDING](https://buildtest.e.ip.saba.us/#/buildrequests/211) | N/A | N/A |
| [package_win32](https://buildtest.e.ip.saba.us/#/builders/36) | [PENDING](https://buildtest.e.ip.saba.us/#/buildrequests/207) | N/A | N/A |
| [package_win64](https://buildtest.e.ip.saba.us/#/builders/59) | [PENDING](https://buildtest.e.ip.saba.us/#/buildrequests/209) | N/A | N/A |

**Comment by staticfloat** [comment]
@jlbuild 61a291bf6c4b5997b9b1371a7d3f12a6ce86945a
```
versioninfo()
```

**Comment by jlbuild** [comment]
## Status of https://github.com/JuliaLang/julia/commit/61a291bf6c4b5997b9b1371a7d3f12a6ce86945a builds:

| Builder Name | Status | Download | Code Output |
| :----------- | :----: | :------: | :---------: |
| [package_linux32](https://buildtest.e.ip.saba.us/#/builders/39) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/39/builds/20) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/x86/0.6/julia-61a291bf6c-linux32.tar.gz) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/65/builds/8)|
| [package_linux64](https://buildtest.e.ip.saba.us/#/builders/54) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/54/builds/18) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/x64/0.6/julia-61a291bf6c-linux64.tar.gz) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/63/builds/18)|
| [package_linuxaarch64](https://buildtest.e.ip.saba.us/#/builders/56) | [ERRORED](https://buildtest.e.ip.saba.us/#/builders/56/builds/17) | N/A | N/A |
| [package_linuxarmv7l](https://buildtest.e.ip.saba.us/#/builders/3) | [ERRORED](https://buildtest.e.ip.saba.us/#/builders/3/builds/24) | N/A | N/A |
| [package_linuxppc64le](https://buildtest.e.ip.saba.us/#/builders/20) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/20/builds/9) | [Download](https://julianightlies.s3.amazonaws.com/test/bin/linux/ppc64le/0.6/julia-61a291bf6c-linuxppc64.tar.gz) | [COMPLETE](https://buildtest.e.ip.saba.us/#/builders/62/builds/9)|
| [package_osx64](https://buildtest.e.ip.saba.us/#/builders/1) | [PENDING](https://buildtest.e.ip.saba.us/#/buildrequests/219) | N/A | N/A |
| [package_win32](https://buildtest.e.ip.saba.us/#/builders/36) | [PENDING](https://buildtest.e.ip.saba.us/#/buildrequests/215) | N/A | N/A |
| [package_win64](https://buildtest.e.ip.saba.us/#/builders/59) | [PENDING](https://buildtest.e.ip.saba.us/#/buildrequests/217) | N/A | N/A |

**Pull request closed without merging**
